### ISSUE TITLE
Potential flaws in practice

### ISSUE THREAD

**Issue by frankshaka** [eleven-huang/InsertRectangleDemo#1]
In the following example, I tried to place new blue boxes at the mouse cursor location, and they were actually placed to the right of other boxes, rather than on top of them (which should visually be closer to the mouse location).

It seems that, when some adjacent "space boxes" are small in widths or heights (e.g. those in the center and on top of others in this example), they tend to reject accepting new target boxes, even though the "combined area" of them are large enough to contain those target boxes.

Any thoughts on how to improve this?

<img width="1146" alt="Screen Shot 2020-09-09 at 16 06 00 3" src="https://user-images.githubusercontent.com/1614752/92574477-b8b59180-f2b9-11ea-8f75-d195d679a05d.png">

<img width="1146" alt="Screen Shot 2020-09-09 at 16 07 59" src="https://user-images.githubusercontent.com/1614752/92573038-ccf88f00-f2b7-11ea-91bd-200bc78dfc02.png">

<img width="1146" alt="Screen Shot 2020-09-09 at 16 08 04" src="https://user-images.githubusercontent.com/1614752/92573055-d124ac80-f2b7-11ea-94b8-caa3f11bee24.png">

<img width="1146" alt="Screen Shot 2020-09-09 at 16 08 14" src="https://user-images.githubusercontent.com/1614752/92573079-d71a8d80-f2b7-11ea-9eb4-666eb052b32a.png">

**Comment by eleven-huang** [comment]
This is actually a path finding bug, and it has been fixed.  
https://github.com/eleven-huang/InsertRectangleDemo/commit/beaf3d734994e9dbaeef0387c706dc6da8209819

**Comment by eleven-huang** [comment]
@frankshaka
